# Generated by Django 4.2.7 on 2024-04-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='наименование категории')),
                ('category_description', models.CharField(max_length=100, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='наименование товара')),
                ('product_description', models.CharField(max_length=100, verbose_name='описание товара')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='превью')),
                ('price', models.IntegerField(verbose_name='цена за покупку')),
                ('create_date', models.DateField(verbose_name='дата создания')),
                ('final_change_date', models.DateField(verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='наименование категории')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
